from turtle import *
t=Turtle()
wn=Screen()
wn.bgcolor("black")
t.color("yellow","cyan")
t.speed(1)
t.begin_fill()
for i in range(4):
    t.left(90)
    t.forward(100)
t.end_fill()
t.penup()    
t.forward(150)
t.pendown()
t.begin_fill()
t.circle(100)
t.end_fill()
t.penup()
t.right(90)    
t.forward(150)
t.pendown()
t.begin_fill()
t.right(75)
t.forward(100)
for i in range(4):
    t.right(144)
    t.forward(100)
t.end_fill()
t.penup()
t.backward(450)
t.pendown()
t.begin_fill()
t.circle(100,180)
t.left(90)
t.forward(200)
t.end_fill()
done()